/**
 * Bulk Job Seeder — 25+ jobs per category
 * Run: node seed_jobs.js
 */
require('dotenv').config();
const mongoose = require('mongoose');
const slugify = require('slugify');
const User = require('./models/User');
const Job = require('./models/Job');
const Company = require('./models/Company');

const COMPANIES = [
    { name: 'Google', industry: 'Technology', logo: 'https://logo.clearbit.com/google.com', location: 'Mountain View, CA' },
    { name: 'Microsoft', industry: 'Technology', logo: 'https://logo.clearbit.com/microsoft.com', location: 'Redmond, WA' },
    { name: 'Amazon', industry: 'Technology', logo: 'https://logo.clearbit.com/amazon.com', location: 'Seattle, WA' },
    { name: 'Meta', industry: 'Technology', logo: 'https://logo.clearbit.com/meta.com', location: 'Menlo Park, CA' },
    { name: 'Apple', industry: 'Technology', logo: 'https://logo.clearbit.com/apple.com', location: 'Cupertino, CA' },
    { name: 'TCS', industry: 'Technology', logo: 'https://logo.clearbit.com/tcs.com', location: 'Mumbai, India' },
    { name: 'Infosys', industry: 'Technology', logo: 'https://logo.clearbit.com/infosys.com', location: 'Bangalore, India' },
    { name: 'Wipro', industry: 'Technology', logo: 'https://logo.clearbit.com/wipro.com', location: 'Pune, India' },
    { name: 'Adobe', industry: 'Design', logo: 'https://logo.clearbit.com/adobe.com', location: 'San Jose, CA' },
    { name: 'Canva', industry: 'Design', logo: 'https://logo.clearbit.com/canva.com', location: 'Sydney, Australia' },
    { name: 'HubSpot', industry: 'Marketing', logo: 'https://logo.clearbit.com/hubspot.com', location: 'Boston, MA' },
    { name: 'Salesforce', industry: 'Technology', logo: 'https://logo.clearbit.com/salesforce.com', location: 'San Francisco, CA' },
    { name: 'JPMorgan', industry: 'Finance', logo: 'https://logo.clearbit.com/jpmorgan.com', location: 'New York, NY' },
    { name: 'Goldman Sachs', industry: 'Finance', logo: 'https://logo.clearbit.com/goldmansachs.com', location: 'New York, NY' },
    { name: 'Deloitte', industry: 'Finance', logo: 'https://logo.clearbit.com/deloitte.com', location: 'Chicago, IL' },
    { name: 'Apollo Hospitals', industry: 'Healthcare', logo: 'https://logo.clearbit.com/apollohospitals.com', location: 'Chennai, India' },
    { name: 'Medtronic', industry: 'Healthcare', logo: 'https://logo.clearbit.com/medtronic.com', location: 'Dublin, Ireland' },
    { name: 'Coursera', industry: 'Education', logo: 'https://logo.clearbit.com/coursera.org', location: 'Mountain View, CA' },
    { name: 'Byju\'s', industry: 'Education', logo: 'https://logo.clearbit.com/byjus.com', location: 'Bangalore, India' },
    { name: 'Siemens', industry: 'Engineering', logo: 'https://logo.clearbit.com/siemens.com', location: 'Munich, Germany' },
    { name: 'Bosch', industry: 'Engineering', logo: 'https://logo.clearbit.com/bosch.com', location: 'Stuttgart, Germany' },
    { name: 'L&T', industry: 'Engineering', logo: 'https://logo.clearbit.com/larsentoubro.com', location: 'Mumbai, India' },
    { name: 'Netflix', industry: 'Technology', logo: 'https://logo.clearbit.com/netflix.com', location: 'Los Gatos, CA' },
    { name: 'Uber', industry: 'Technology', logo: 'https://logo.clearbit.com/uber.com', location: 'San Francisco, CA' },
    { name: 'Airbnb', industry: 'Technology', logo: 'https://logo.clearbit.com/airbnb.com', location: 'San Francisco, CA' },
];

const JOBS = [
    // ─── TECHNOLOGY ───────────────────────────────────────────────
    { title: 'Frontend Developer', category: 'technology', company: 'Google', experience: '2-4 years', salary: { min: 120000, max: 180000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['React', 'TypeScript', 'CSS'], type: 'full-time' },
    { title: 'Backend Engineer', category: 'technology', company: 'Amazon', experience: '3-6 years', salary: { min: 140000, max: 210000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Java', 'Spring Boot', 'AWS'], type: 'full-time' },
    { title: 'Full Stack Developer', category: 'technology', company: 'Microsoft', experience: '2-5 years', salary: { min: 130000, max: 200000, currency: 'USD' }, location: 'Redmond, WA', skills: ['React', 'Node.js', 'Azure'], type: 'full-time' },
    { title: 'Mobile App Developer (Android)', category: 'technology', company: 'Meta', experience: '2-4 years', salary: { min: 140000, max: 200000, currency: 'USD' }, location: 'Menlo Park, CA', skills: ['Kotlin', 'Android SDK', 'Firebase'], type: 'full-time' },
    { title: 'iOS Developer', category: 'technology', company: 'Apple', experience: '3-6 years', salary: { min: 150000, max: 220000, currency: 'USD' }, location: 'Cupertino, CA', skills: ['Swift', 'Xcode', 'Core Data'], type: 'full-time' },
    { title: 'DevOps Engineer', category: 'technology', company: 'Netflix', experience: '3-6 years', salary: { min: 140000, max: 210000, currency: 'USD' }, location: 'Los Gatos, CA', skills: ['Kubernetes', 'Docker', 'CI/CD'], type: 'full-time' },
    { title: 'Cloud Solutions Architect', category: 'technology', company: 'Amazon', experience: '6-10 years', salary: { min: 180000, max: 260000, currency: 'USD' }, location: 'Remote', skills: ['AWS', 'Terraform', 'Serverless'], type: 'full-time' },
    { title: 'Site Reliability Engineer', category: 'technology', company: 'Google', experience: '4-8 years', salary: { min: 160000, max: 240000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Python', 'Linux', 'Monitoring'], type: 'full-time' },
    { title: 'Cybersecurity Analyst', category: 'technology', company: 'Microsoft', experience: '3-5 years', salary: { min: 120000, max: 175000, currency: 'USD' }, location: 'Redmond, WA', skills: ['SIEM', 'Penetration Testing', 'CISSP'], type: 'full-time' },
    { title: 'Blockchain Developer', category: 'technology', company: 'Uber', experience: '2-5 years', salary: { min: 130000, max: 190000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Solidity', 'Ethereum', 'Web3.js'], type: 'full-time' },
    { title: 'Software Engineer', category: 'technology', company: 'TCS', experience: '1-3 years', salary: { min: 600000, max: 1200000, currency: 'INR' }, location: 'Bangalore, India', skills: ['Java', 'SQL', 'REST APIs'], type: 'full-time' },
    { title: 'React Native Developer', category: 'technology', company: 'Infosys', experience: '2-4 years', salary: { min: 800000, max: 1600000, currency: 'INR' }, location: 'Pune, India', skills: ['React Native', 'Redux', 'JavaScript'], type: 'full-time' },
    { title: 'Python Developer', category: 'technology', company: 'Wipro', experience: '2-5 years', salary: { min: 750000, max: 1400000, currency: 'INR' }, location: 'Hyderabad, India', skills: ['Python', 'Django', 'PostgreSQL'], type: 'full-time' },
    { title: 'QA Automation Engineer', category: 'technology', company: 'Salesforce', experience: '2-4 years', salary: { min: 110000, max: 160000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Selenium', 'Cypress', 'Jest'], type: 'full-time' },
    { title: 'Embedded Systems Engineer', category: 'technology', company: 'Apple', experience: '3-6 years', salary: { min: 140000, max: 200000, currency: 'USD' }, location: 'Cupertino, CA', skills: ['C/C++', 'RTOS', 'ARM'], type: 'full-time' },
    { title: 'Technical Product Manager', category: 'technology', company: 'Airbnb', experience: '5-9 years', salary: { min: 170000, max: 240000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Product Strategy', 'Agile', 'APIs'], type: 'full-time' },
    { title: 'Machine Learning Engineer', category: 'technology', company: 'Google', experience: '3-7 years', salary: { min: 160000, max: 250000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['Python', 'TensorFlow', 'MLOps'], type: 'full-time' },
    { title: 'UI/UX Engineer', category: 'technology', company: 'Meta', experience: '2-5 years', salary: { min: 130000, max: 195000, currency: 'USD' }, location: 'Menlo Park, CA', skills: ['Figma', 'React', 'Design Systems'], type: 'full-time' },
    { title: 'Database Administrator', category: 'technology', company: 'TCS', experience: '3-7 years', salary: { min: 900000, max: 1800000, currency: 'INR' }, location: 'Chennai, India', skills: ['MySQL', 'Oracle', 'Performance Tuning'], type: 'full-time' },
    { title: 'Solutions Engineer', category: 'technology', company: 'Salesforce', experience: '3-5 years', salary: { min: 120000, max: 170000, currency: 'USD' }, location: 'Remote', skills: ['Salesforce CRM', 'Apex', 'REST APIs'], type: 'full-time' },
    { title: 'Data Engineer', category: 'technology', company: 'Uber', experience: '3-6 years', salary: { min: 140000, max: 200000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Spark', 'Kafka', 'Airflow'], type: 'full-time' },
    { title: 'AR/VR Developer', category: 'technology', company: 'Meta', experience: '2-5 years', salary: { min: 140000, max: 210000, currency: 'USD' }, location: 'Menlo Park, CA', skills: ['Unity', 'C#', 'OpenXR'], type: 'full-time' },
    { title: 'Platform Engineer', category: 'technology', company: 'Netflix', experience: '4-8 years', salary: { min: 160000, max: 230000, currency: 'USD' }, location: 'Los Gatos, CA', skills: ['Go', 'Kubernetes', 'Distributed Systems'], type: 'full-time' },
    { title: 'API Developer', category: 'technology', company: 'Microsoft', experience: '2-4 years', salary: { min: 120000, max: 175000, currency: 'USD' }, location: 'Redmond, WA', skills: ['REST', 'GraphQL', 'Node.js'], type: 'full-time' },
    { title: 'Junior Software Engineer', category: 'technology', company: 'Wipro', experience: '0-1 years', salary: { min: 400000, max: 700000, currency: 'INR' }, location: 'Remote', skills: ['JavaScript', 'HTML', 'CSS'], type: 'full-time' },

    // ─── DESIGN ───────────────────────────────────────────────────
    { title: 'UI/UX Designer', category: 'design', company: 'Adobe', experience: '2-5 years', salary: { min: 90000, max: 140000, currency: 'USD' }, location: 'San Jose, CA', skills: ['Figma', 'Adobe XD', 'Prototyping'], type: 'full-time' },
    { title: 'Product Designer', category: 'design', company: 'Airbnb', experience: '3-6 years', salary: { min: 120000, max: 180000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Design Systems', 'User Research', 'Figma'], type: 'full-time' },
    { title: 'Graphic Designer', category: 'design', company: 'Canva', experience: '1-3 years', salary: { min: 70000, max: 100000, currency: 'USD' }, location: 'Remote', skills: ['Illustrator', 'Photoshop', 'Typography'], type: 'full-time' },
    { title: 'Motion Graphics Designer', category: 'design', company: 'Netflix', experience: '3-5 years', salary: { min: 100000, max: 150000, currency: 'USD' }, location: 'Los Gatos, CA', skills: ['After Effects', 'Cinema 4D', 'Motion Design'], type: 'full-time' },
    { title: 'Brand Designer', category: 'design', company: 'Airbnb', experience: '4-7 years', salary: { min: 115000, max: 165000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Branding', 'Figma', 'Illustration'], type: 'full-time' },
    { title: 'Visual Designer', category: 'design', company: 'Meta', experience: '2-4 years', salary: { min: 110000, max: 160000, currency: 'USD' }, location: 'Menlo Park, CA', skills: ['Visual Design', 'Adobe Creative Suite', 'CSS'], type: 'full-time' },
    { title: 'Interaction Designer', category: 'design', company: 'Google', experience: '3-6 years', salary: { min: 120000, max: 175000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['Interaction Design', 'Figma', 'Usability Testing'], type: 'full-time' },
    { title: 'UX Researcher', category: 'design', company: 'Microsoft', experience: '2-5 years', salary: { min: 105000, max: 155000, currency: 'USD' }, location: 'Redmond, WA', skills: ['User Research', 'A/B Testing', 'Analytics'], type: 'full-time' },
    { title: '3D Artist', category: 'design', company: 'Apple', experience: '3-6 years', salary: { min: 110000, max: 160000, currency: 'USD' }, location: 'Cupertino, CA', skills: ['Blender', 'Cinema 4D', 'ZBrush'], type: 'full-time' },
    { title: 'Design Systems Engineer', category: 'design', company: 'Salesforce', experience: '4-7 years', salary: { min: 125000, max: 180000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Figma Tokens', 'Storybook', 'React'], type: 'full-time' },
    { title: 'Creative Director', category: 'design', company: 'Adobe', experience: '8-12 years', salary: { min: 150000, max: 210000, currency: 'USD' }, location: 'San Jose, CA', skills: ['Creative Leadership', 'Brand Strategy', 'Art Direction'], type: 'full-time' },
    { title: 'Web Designer', category: 'design', company: 'HubSpot', experience: '1-3 years', salary: { min: 65000, max: 95000, currency: 'USD' }, location: 'Boston, MA', skills: ['HTML', 'CSS', 'Figma'], type: 'full-time' },
    { title: 'Illustrator', category: 'design', company: 'Canva', experience: '2-4 years', salary: { min: 75000, max: 110000, currency: 'USD' }, location: 'Remote', skills: ['Illustration', 'Adobe Illustrator', 'Procreate'], type: 'full-time' },
    { title: 'Accessibility Designer', category: 'design', company: 'Microsoft', experience: '3-6 years', salary: { min: 110000, max: 160000, currency: 'USD' }, location: 'Redmond, WA', skills: ['WCAG', 'Inclusive Design', 'Screen Readers'], type: 'full-time' },
    { title: 'Packaging Designer', category: 'design', company: 'Apple', experience: '4-7 years', salary: { min: 110000, max: 155000, currency: 'USD' }, location: 'Cupertino, CA', skills: ['Packaging', 'Print Design', 'CAD'], type: 'full-time' },
    { title: 'Game UI Designer', category: 'design', company: 'Meta', experience: '2-5 years', salary: { min: 105000, max: 155000, currency: 'USD' }, location: 'Menlo Park, CA', skills: ['Unity UI', 'Game Design', 'Figma'], type: 'full-time' },
    { title: 'Typography Specialist', category: 'design', company: 'Adobe', experience: '4-8 years', salary: { min: 100000, max: 145000, currency: 'USD' }, location: 'San Jose, CA', skills: ['Typography', 'Font Design', 'OpenType'], type: 'full-time' },
    { title: 'Content Designer', category: 'design', company: 'Airbnb', experience: '2-5 years', salary: { min: 100000, max: 145000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['UX Writing', 'Content Strategy', 'Figma'], type: 'full-time' },
    { title: 'Design Lead', category: 'design', company: 'Google', experience: '6-10 years', salary: { min: 150000, max: 220000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['Design Leadership', 'Figma', 'Product Strategy'], type: 'full-time' },
    { title: 'UI Developer', category: 'design', company: 'Canva', experience: '2-4 years', salary: { min: 80000, max: 120000, currency: 'USD' }, location: 'Remote', skills: ['HTML', 'CSS', 'Vue.js'], type: 'full-time' },
    { title: 'Print Designer', category: 'design', company: 'HubSpot', experience: '1-3 years', salary: { min: 60000, max: 85000, currency: 'USD' }, location: 'Boston, MA', skills: ['InDesign', 'Print Production', 'Color Theory'], type: 'full-time' },
    { title: 'Design Intern', category: 'design', company: 'Canva', experience: '0-1 years', salary: { min: 50000, max: 70000, currency: 'USD' }, location: 'Remote', skills: ['Figma', 'Canva', 'Basic Design'], type: 'internship' },
    { title: 'Experience Designer', category: 'design', company: 'Microsoft', experience: '3-7 years', salary: { min: 115000, max: 170000, currency: 'USD' }, location: 'Redmond, WA', skills: ['CX Design', 'Figma', 'Service Design'], type: 'full-time' },
    { title: 'Video Editor', category: 'design', company: 'Netflix', experience: '2-5 years', salary: { min: 85000, max: 125000, currency: 'USD' }, location: 'Los Gatos, CA', skills: ['Premiere Pro', 'Final Cut', 'Color Grading'], type: 'full-time' },
    { title: 'Photo Editor', category: 'design', company: 'Airbnb', experience: '1-3 years', salary: { min: 65000, max: 95000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Lightroom', 'Photoshop', 'Color Correction'], type: 'full-time' },

    // ─── MARKETING ────────────────────────────────────────────────
    { title: 'Digital Marketing Manager', category: 'marketing', company: 'HubSpot', experience: '4-7 years', salary: { min: 90000, max: 135000, currency: 'USD' }, location: 'Boston, MA', skills: ['SEO', 'PPC', 'Analytics'], type: 'full-time' },
    { title: 'Content Marketing Strategist', category: 'marketing', company: 'Salesforce', experience: '3-6 years', salary: { min: 85000, max: 125000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Content Strategy', 'SEO Writing', 'CMS'], type: 'full-time' },
    { title: 'Social Media Manager', category: 'marketing', company: 'Airbnb', experience: '2-4 years', salary: { min: 70000, max: 100000, currency: 'USD' }, location: 'Remote', skills: ['Instagram', 'TikTok', 'Community Management'], type: 'full-time' },
    { title: 'SEO Specialist', category: 'marketing', company: 'HubSpot', experience: '2-5 years', salary: { min: 75000, max: 110000, currency: 'USD' }, location: 'Boston, MA', skills: ['On-Page SEO', 'Link Building', 'Google Search Console'], type: 'full-time' },
    { title: 'Email Marketing Manager', category: 'marketing', company: 'Salesforce', experience: '3-5 years', salary: { min: 80000, max: 115000, currency: 'USD' }, location: 'Remote', skills: ['Pardot', 'A/B Testing', 'Segmentation'], type: 'full-time' },
    { title: 'Growth Marketing Lead', category: 'marketing', company: 'Uber', experience: '4-8 years', salary: { min: 120000, max: 175000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Growth Hacking', 'SQL', 'Experimentation'], type: 'full-time' },
    { title: 'Brand Marketing Manager', category: 'marketing', company: 'Meta', experience: '5-9 years', salary: { min: 130000, max: 185000, currency: 'USD' }, location: 'Menlo Park, CA', skills: ['Brand Management', 'Campaign Planning', 'Creative Brief'], type: 'full-time' },
    { title: 'Performance Marketing Analyst', category: 'marketing', company: 'Netflix', experience: '2-4 years', salary: { min: 85000, max: 120000, currency: 'USD' }, location: 'Los Gatos, CA', skills: ['Google Ads', 'Facebook Ads', 'Attribution Modeling'], type: 'full-time' },
    { title: 'Product Marketing Manager', category: 'marketing', company: 'Microsoft', experience: '5-8 years', salary: { min: 130000, max: 190000, currency: 'USD' }, location: 'Redmond, WA', skills: ['Go-to-Market', 'Competitive Analysis', 'Messaging'], type: 'full-time' },
    { title: 'PR & Communications Manager', category: 'marketing', company: 'Google', experience: '5-9 years', salary: { min: 120000, max: 175000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['Media Relations', 'Crisis Communications', 'Press Releases'], type: 'full-time' },
    { title: 'Influencer Marketing Manager', category: 'marketing', company: 'Canva', experience: '3-5 years', salary: { min: 75000, max: 110000, currency: 'USD' }, location: 'Remote', skills: ['Influencer Outreach', 'Campaign Management', 'Analytics'], type: 'full-time' },
    { title: 'Marketing Analyst', category: 'marketing', company: 'HubSpot', experience: '1-3 years', salary: { min: 65000, max: 90000, currency: 'USD' }, location: 'Boston, MA', skills: ['Google Analytics', 'Excel', 'Data Viz'], type: 'full-time' },
    { title: 'Affiliate Marketing Specialist', category: 'marketing', company: 'Amazon', experience: '2-4 years', salary: { min: 80000, max: 115000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Affiliate Networks', 'Commission Tracking', 'CRO'], type: 'full-time' },
    { title: 'Video Marketing Producer', category: 'marketing', company: 'Airbnb', experience: '3-6 years', salary: { min: 90000, max: 130000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Video Production', 'YouTube', 'Scriptwriting'], type: 'full-time' },
    { title: 'CRM Marketing Manager', category: 'marketing', company: 'Uber', experience: '4-7 years', salary: { min: 105000, max: 155000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['CRM', 'Lifecycle Marketing', 'Push Notifications'], type: 'full-time' },
    { title: 'Event Marketing Manager', category: 'marketing', company: 'Salesforce', experience: '4-7 years', salary: { min: 95000, max: 140000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Event Planning', 'Lead Generation', 'Budget Management'], type: 'full-time' },
    { title: 'Market Research Analyst', category: 'marketing', company: 'Microsoft', experience: '2-4 years', salary: { min: 75000, max: 105000, currency: 'USD' }, location: 'Redmond, WA', skills: ['Primary Research', 'Focus Groups', 'SPSS'], type: 'full-time' },
    { title: 'Copywriter', category: 'marketing', company: 'HubSpot', experience: '2-5 years', salary: { min: 70000, max: 100000, currency: 'USD' }, location: 'Remote', skills: ['Copywriting', 'Brand Voice', 'Ad Copy'], type: 'full-time' },
    { title: 'Account-Based Marketing Manager', category: 'marketing', company: 'Salesforce', experience: '5-8 years', salary: { min: 115000, max: 165000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['ABM', 'Marketo', 'Sales Alignment'], type: 'full-time' },
    { title: 'Head of Marketing', category: 'marketing', company: 'Canva', experience: '10-15 years', salary: { min: 180000, max: 250000, currency: 'USD' }, location: 'Sydney, Australia', skills: ['Marketing Strategy', 'Team Leadership', 'P&L Management'], type: 'full-time' },
    { title: 'Marketing Coordinator', category: 'marketing', company: 'HubSpot', experience: '0-2 years', salary: { min: 50000, max: 70000, currency: 'USD' }, location: 'Boston, MA', skills: ['HubSpot CRM', 'Social Media', 'Content Creation'], type: 'full-time' },
    { title: 'Programmatic Advertising Specialist', category: 'marketing', company: 'Meta', experience: '3-6 years', salary: { min: 95000, max: 140000, currency: 'USD' }, location: 'Menlo Park, CA', skills: ['DSP/SSP', 'DV360', 'Audience Targeting'], type: 'full-time' },
    { title: 'Marketing Automation Specialist', category: 'marketing', company: 'Salesforce', experience: '2-5 years', salary: { min: 80000, max: 115000, currency: 'USD' }, location: 'Remote', skills: ['Marketo', 'Pardot', 'Workflow Automation'], type: 'full-time' },
    { title: 'Community Manager', category: 'marketing', company: 'Airbnb', experience: '2-4 years', salary: { min: 65000, max: 90000, currency: 'USD' }, location: 'Remote', skills: ['Community Building', 'Discord', 'Engagement'], type: 'full-time' },
    { title: 'Field Marketing Manager', category: 'marketing', company: 'Microsoft', experience: '4-7 years', salary: { min: 100000, max: 145000, currency: 'USD' }, location: 'Chicago, IL', skills: ['Field Events', 'Pipeline Generation', 'SFDC'], type: 'full-time' },

    // ─── FINANCE ──────────────────────────────────────────────────
    { title: 'Investment Analyst', category: 'finance', company: 'JPMorgan', experience: '2-4 years', salary: { min: 100000, max: 160000, currency: 'USD' }, location: 'New York, NY', skills: ['Financial Modeling', 'Excel', 'Valuation'], type: 'full-time' },
    { title: 'Financial Analyst', category: 'finance', company: 'Goldman Sachs', experience: '1-3 years', salary: { min: 90000, max: 140000, currency: 'USD' }, location: 'New York, NY', skills: ['FP&A', 'Excel', 'SAP'], type: 'full-time' },
    { title: 'Risk Analyst', category: 'finance', company: 'JPMorgan', experience: '3-6 years', salary: { min: 110000, max: 165000, currency: 'USD' }, location: 'New York, NY', skills: ['Credit Risk', 'VaR', 'Python'], type: 'full-time' },
    { title: 'Chartered Accountant', category: 'finance', company: 'Deloitte', experience: '3-6 years', salary: { min: 1200000, max: 2500000, currency: 'INR' }, location: 'Mumbai, India', skills: ['IFRS', 'Tax', 'Audit'], type: 'full-time' },
    { title: 'Controller', category: 'finance', company: 'Amazon', experience: '8-12 years', salary: { min: 180000, max: 260000, currency: 'USD' }, location: 'Seattle, WA', skills: ['GAAP', 'Consolidation', 'ERP'], type: 'full-time' },
    { title: 'Tax Manager', category: 'finance', company: 'Deloitte', experience: '5-9 years', salary: { min: 120000, max: 175000, currency: 'USD' }, location: 'Chicago, IL', skills: ['Corporate Tax', 'Transfer Pricing', 'R&D Credits'], type: 'full-time' },
    { title: 'VP of Finance', category: 'finance', company: 'Netflix', experience: '12-16 years', salary: { min: 250000, max: 350000, currency: 'USD' }, location: 'Los Gatos, CA', skills: ['Strategic Finance', 'Forecasting', 'Investor Relations'], type: 'full-time' },
    { title: 'Treasury Manager', category: 'finance', company: 'Goldman Sachs', experience: '6-10 years', salary: { min: 140000, max: 200000, currency: 'USD' }, location: 'New York, NY', skills: ['Cash Management', 'FX Hedging', 'Treasury Systems'], type: 'full-time' },
    { title: 'Equity Research Analyst', category: 'finance', company: 'Goldman Sachs', experience: '3-6 years', salary: { min: 130000, max: 185000, currency: 'USD' }, location: 'New York, NY', skills: ['Equity Research', 'DCF', 'Bloomberg'], type: 'full-time' },
    { title: 'Audit Manager', category: 'finance', company: 'Deloitte', experience: '5-9 years', salary: { min: 110000, max: 160000, currency: 'USD' }, location: 'Chicago, IL', skills: ['Internal Audit', 'SOX', 'Risk Assessment'], type: 'full-time' },
    { title: 'Quantitative Analyst', category: 'finance', company: 'JPMorgan', experience: '3-7 years', salary: { min: 150000, max: 220000, currency: 'USD' }, location: 'New York, NY', skills: ['Python', 'Statistics', 'Derivatives Pricing'], type: 'full-time' },
    { title: 'Compliance Officer', category: 'finance', company: 'Goldman Sachs', experience: '4-8 years', salary: { min: 120000, max: 175000, currency: 'USD' }, location: 'New York, NY', skills: ['KYC/AML', 'Regulatory Compliance', 'FINRA'], type: 'full-time' },
    { title: 'Finance Business Partner', category: 'finance', company: 'Microsoft', experience: '6-10 years', salary: { min: 150000, max: 210000, currency: 'USD' }, location: 'Redmond, WA', skills: ['Business Partnering', 'P&L', 'Data Analysis'], type: 'full-time' },
    { title: 'Credit Analyst', category: 'finance', company: 'JPMorgan', experience: '2-4 years', salary: { min: 90000, max: 130000, currency: 'USD' }, location: 'Chicago, IL', skills: ['Credit Analysis', 'Underwriting', 'Financial Statements'], type: 'full-time' },
    { title: 'Accountant', category: 'finance', company: 'Deloitte', experience: '1-3 years', salary: { min: 65000, max: 90000, currency: 'USD' }, location: 'Chicago, IL', skills: ['GAAP', 'QuickBooks', 'Month-End Close'], type: 'full-time' },
    { title: 'Mergers & Acquisitions Analyst', category: 'finance', company: 'Goldman Sachs', experience: '2-5 years', salary: { min: 120000, max: 180000, currency: 'USD' }, location: 'New York, NY', skills: ['M&A Modeling', 'Due Diligence', 'Pitchbooks'], type: 'full-time' },
    { title: 'Payroll Manager', category: 'finance', company: 'Amazon', experience: '4-7 years', salary: { min: 90000, max: 130000, currency: 'USD' }, location: 'Seattle, WA', skills: ['ADP', 'Payroll Processing', 'Multi-State Tax'], type: 'full-time' },
    { title: 'Insurance Underwriter', category: 'finance', company: 'JPMorgan', experience: '3-6 years', salary: { min: 90000, max: 135000, currency: 'USD' }, location: 'New York, NY', skills: ['Risk Assessment', 'Actuarial Tables', 'Policy Writing'], type: 'full-time' },
    { title: 'CFO', category: 'finance', company: 'Airbnb', experience: '15+ years', salary: { min: 400000, max: 600000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Strategic Leadership', 'IPO Experience', 'Capital Allocation'], type: 'full-time' },
    { title: 'Financial Planning Analyst', category: 'finance', company: 'Netflix', experience: '2-5 years', salary: { min: 100000, max: 145000, currency: 'USD' }, location: 'Los Gatos, CA', skills: ['FP&A', 'Adaptive Insights', 'Scenario Modeling'], type: 'full-time' },
    { title: 'Private Equity Associate', category: 'finance', company: 'Goldman Sachs', experience: '2-4 years', salary: { min: 140000, max: 200000, currency: 'USD' }, location: 'New York, NY', skills: ['LBO Modeling', 'Deal Sourcing', 'Portfolio Management'], type: 'full-time' },
    { title: 'Bookkeeper', category: 'finance', company: 'Deloitte', experience: '1-3 years', salary: { min: 50000, max: 70000, currency: 'USD' }, location: 'Remote', skills: ['QuickBooks', 'Bank Reconciliation', 'AP/AR'], type: 'full-time' },
    { title: 'Cost Accountant', category: 'finance', company: 'Amazon', experience: '3-6 years', salary: { min: 85000, max: 120000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Cost Accounting', 'Variance Analysis', 'Inventory'], type: 'full-time' },
    { title: 'Wealth Manager', category: 'finance', company: 'JPMorgan', experience: '6-12 years', salary: { min: 130000, max: 200000, currency: 'USD' }, location: 'New York, NY', skills: ['Portfolio Management', 'Client Relations', 'Estate Planning'], type: 'full-time' },
    { title: 'Finance Intern', category: 'finance', company: 'Goldman Sachs', experience: '0-1 years', salary: { min: 70000, max: 90000, currency: 'USD' }, location: 'New York, NY', skills: ['Excel', 'Financial Modeling Basics', 'PowerPoint'], type: 'internship' },

    // ─── HEALTHCARE ───────────────────────────────────────────────
    { title: 'Clinical Data Scientist', category: 'healthcare', company: 'Medtronic', experience: '3-6 years', salary: { min: 110000, max: 165000, currency: 'USD' }, location: 'Dublin, Ireland', skills: ['R', 'Clinical Trials', 'SAS'], type: 'full-time' },
    { title: 'Healthcare Administrator', category: 'healthcare', company: 'Apollo Hospitals', experience: '4-8 years', salary: { min: 1200000, max: 2200000, currency: 'INR' }, location: 'Chennai, India', skills: ['Hospital Management', 'HMIS', 'Quality Standards'], type: 'full-time' },
    { title: 'Biomedical Engineer', category: 'healthcare', company: 'Medtronic', experience: '2-5 years', salary: { min: 90000, max: 135000, currency: 'USD' }, location: 'Dublin, Ireland', skills: ['Medical Devices', 'FDA Regulations', 'R&D'], type: 'full-time' },
    { title: 'Nurse Practitioner', category: 'healthcare', company: 'Apollo Hospitals', experience: '3-6 years', salary: { min: 1500000, max: 2800000, currency: 'INR' }, location: 'Mumbai, India', skills: ['Patient Care', 'Diagnosis', 'Clinical Procedures'], type: 'full-time' },
    { title: 'Health IT Specialist', category: 'healthcare', company: 'Medtronic', experience: '3-5 years', salary: { min: 90000, max: 130000, currency: 'USD' }, location: 'Remote', skills: ['Electronic Health Records', 'HL7', 'FHIR'], type: 'full-time' },
    { title: 'Pharmacist', category: 'healthcare', company: 'Apollo Hospitals', experience: '2-5 years', salary: { min: 800000, max: 1600000, currency: 'INR' }, location: 'Hyderabad, India', skills: ['Dispensing', 'Drug Interactions', 'Patient Counseling'], type: 'full-time' },
    { title: 'Radiologist', category: 'healthcare', company: 'Apollo Hospitals', experience: '5-10 years', salary: { min: 3000000, max: 6000000, currency: 'INR' }, location: 'Delhi, India', skills: ['MRI', 'CT Scan', 'Image Interpretation'], type: 'full-time' },
    { title: 'Medical Coder', category: 'healthcare', company: 'Apollo Hospitals', experience: '1-3 years', salary: { min: 400000, max: 700000, currency: 'INR' }, location: 'Remote', skills: ['ICD-10', 'CPT Coding', 'CPC Certification'], type: 'full-time' },
    { title: 'Quality Assurance Specialist', category: 'healthcare', company: 'Medtronic', experience: '3-6 years', salary: { min: 90000, max: 135000, currency: 'USD' }, location: 'Dublin, Ireland', skills: ['GMP', 'ISO 13485', 'CAPA'], type: 'full-time' },
    { title: 'Medical Device Engineer', category: 'healthcare', company: 'Medtronic', experience: '4-8 years', salary: { min: 110000, max: 160000, currency: 'USD' }, location: 'Dublin, Ireland', skills: ['Device Design', 'Validation', 'FDA 510(k)'], type: 'full-time' },
    { title: 'Health Coach', category: 'healthcare', company: 'Apollo Hospitals', experience: '2-4 years', salary: { min: 600000, max: 1000000, currency: 'INR' }, location: 'Bangalore, India', skills: ['Nutrition', 'Wellness Programs', 'Motivational Coaching'], type: 'full-time' },
    { title: 'Clinical Research Associate', category: 'healthcare', company: 'Medtronic', experience: '2-4 years', salary: { min: 75000, max: 110000, currency: 'USD' }, location: 'Remote', skills: ['GCP', 'Protocol Adherence', 'Site Management'], type: 'full-time' },
    { title: 'Healthcare Data Analyst', category: 'healthcare', company: 'Apollo Hospitals', experience: '2-5 years', salary: { min: 800000, max: 1500000, currency: 'INR' }, location: 'Chennai, India', skills: ['SQL', 'Power BI', 'Patient Outcomes'], type: 'full-time' },
    { title: 'Physiotherapist', category: 'healthcare', company: 'Apollo Hospitals', experience: '2-5 years', salary: { min: 700000, max: 1200000, currency: 'INR' }, location: 'Mumbai, India', skills: ['Rehabilitation', 'Manual Therapy', 'Exercise Prescription'], type: 'full-time' },
    { title: 'Regulatory Affairs Specialist', category: 'healthcare', company: 'Medtronic', experience: '3-7 years', salary: { min: 95000, max: 140000, currency: 'USD' }, location: 'Dublin, Ireland', skills: ['FDA Submissions', 'CE Marking', 'Regulatory Strategy'], type: 'full-time' },
    { title: 'Hospital Information Systems Manager', category: 'healthcare', company: 'Apollo Hospitals', experience: '5-9 years', salary: { min: 1500000, max: 2800000, currency: 'INR' }, location: 'Chennai, India', skills: ['HMIS', 'EHR Implementation', 'IT Support'], type: 'full-time' },
    { title: 'Patient Experience Specialist', category: 'healthcare', company: 'Apollo Hospitals', experience: '2-4 years', salary: { min: 500000, max: 900000, currency: 'INR' }, location: 'Hyderabad, India', skills: ['Patient Relations', 'HCAHPS', 'Service Recovery'], type: 'full-time' },
    { title: 'Telemedicine Physician', category: 'healthcare', company: 'Apollo Hospitals', experience: '3-8 years', salary: { min: 2000000, max: 4000000, currency: 'INR' }, location: 'Remote', skills: ['General Medicine', 'Telemedicine Platforms', 'Digital Health'], type: 'full-time' },
    { title: 'Biostatistician', category: 'healthcare', company: 'Medtronic', experience: '4-8 years', salary: { min: 110000, max: 160000, currency: 'USD' }, location: 'Dublin, Ireland', skills: ['SAS', 'R', 'Clinical Statistics'], type: 'full-time' },
    { title: 'Lab Technician', category: 'healthcare', company: 'Apollo Hospitals', experience: '1-3 years', salary: { min: 350000, max: 600000, currency: 'INR' }, location: 'Delhi, India', skills: ['Sample Analysis', 'Lab Equipment', 'Quality Control'], type: 'full-time' },
    { title: 'Mental Health Counselor', category: 'healthcare', company: 'Apollo Hospitals', experience: '3-6 years', salary: { min: 800000, max: 1400000, currency: 'INR' }, location: 'Bangalore, India', skills: ['CBT', 'Trauma-Informed Care', 'Group Therapy'], type: 'full-time' },
    { title: 'Epidemiologist', category: 'healthcare', company: 'Medtronic', experience: '4-8 years', salary: { min: 100000, max: 145000, currency: 'USD' }, location: 'Dublin, Ireland', skills: ['Disease Surveillance', 'SPSS', 'Public Health'], type: 'full-time' },
    { title: 'Nutritionist', category: 'healthcare', company: 'Apollo Hospitals', experience: '2-4 years', salary: { min: 600000, max: 1000000, currency: 'INR' }, location: 'Chennai, India', skills: ['Diet Planning', 'Clinical Nutrition', 'Diabetes Management'], type: 'full-time' },
    { title: 'Supply Chain Manager – Medical', category: 'healthcare', company: 'Medtronic', experience: '5-9 years', salary: { min: 120000, max: 175000, currency: 'USD' }, location: 'Dublin, Ireland', skills: ['Medical Supply Chain', 'SAP', 'Vendor Management'], type: 'full-time' },
    { title: 'Healthcare IT Consultant', category: 'healthcare', company: 'Medtronic', experience: '5-9 years', salary: { min: 130000, max: 185000, currency: 'USD' }, location: 'Remote', skills: ['EHR Consulting', 'Epic', 'Process Improvement'], type: 'full-time' },

    // ─── EDUCATION ────────────────────────────────────────────────
    { title: 'Curriculum Developer', category: 'education', company: 'Coursera', experience: '3-6 years', salary: { min: 80000, max: 115000, currency: 'USD' }, location: 'Remote', skills: ['Instructional Design', 'LMS', 'Content Development'], type: 'full-time' },
    { title: 'Online Instructor – Data Science', category: 'education', company: 'Coursera', experience: '3-8 years', salary: { min: 75000, max: 110000, currency: 'USD' }, location: 'Remote', skills: ['Python', 'Machine Learning', 'Teaching'], type: 'full-time' },
    { title: 'E-learning Developer', category: 'education', company: 'Byju\'s', experience: '2-4 years', salary: { min: 700000, max: 1300000, currency: 'INR' }, location: 'Bangalore, India', skills: ['Articulate Storyline', 'Captivate', 'Multimedia'], type: 'full-time' },
    { title: 'Academic Counselor', category: 'education', company: 'Byju\'s', experience: '1-3 years', salary: { min: 500000, max: 900000, currency: 'INR' }, location: 'Hyderabad, India', skills: ['Student Guidance', 'Career Counseling', 'CRM'], type: 'full-time' },
    { title: 'Learning Experience Designer', category: 'education', company: 'Coursera', experience: '3-6 years', salary: { min: 85000, max: 125000, currency: 'USD' }, location: 'Remote', skills: ['UX for Learning', 'Storyboarding', 'LXD'], type: 'full-time' },
    { title: 'University Lecturer – Computer Science', category: 'education', company: 'Coursera', experience: '5-10 years', salary: { min: 90000, max: 135000, currency: 'USD' }, location: 'Remote', skills: ['CS Fundamentals', 'Research', 'Curriculum Planning'], type: 'full-time' },
    { title: 'Teacher – Mathematics', category: 'education', company: 'Byju\'s', experience: '2-5 years', salary: { min: 600000, max: 1000000, currency: 'INR' }, location: 'Remote', skills: ['Mathematics', 'Online Teaching', 'Student Engagement'], type: 'full-time' },
    { title: 'Education Technology Product Manager', category: 'education', company: 'Coursera', experience: '5-9 years', salary: { min: 130000, max: 180000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['EdTech', 'Product Roadmap', 'LMS Integration'], type: 'full-time' },
    { title: 'Student Success Manager', category: 'education', company: 'Byju\'s', experience: '2-5 years', salary: { min: 700000, max: 1200000, currency: 'INR' }, location: 'Bangalore, India', skills: ['Student Retention', 'Onboarding', 'Data Analysis'], type: 'full-time' },
    { title: 'Training & Development Specialist', category: 'education', company: 'Microsoft', experience: '3-6 years', salary: { min: 90000, max: 130000, currency: 'USD' }, location: 'Redmond, WA', skills: ['Corporate Training', 'Facilitation', 'Needs Analysis'], type: 'full-time' },
    { title: 'Special Education Teacher', category: 'education', company: 'Coursera', experience: '3-6 years', salary: { min: 65000, max: 95000, currency: 'USD' }, location: 'Remote', skills: ['IEP Development', 'Adaptive Technology', 'Behavioral Support'], type: 'full-time' },
    { title: 'Academic Operations Manager', category: 'education', company: 'Byju\'s', experience: '5-9 years', salary: { min: 1200000, max: 2200000, currency: 'INR' }, location: 'Bangalore, India', skills: ['Operations', 'Academic Quality', 'Stakeholder Management'], type: 'full-time' },
    { title: 'Language Instructor – English', category: 'education', company: 'Coursera', experience: '2-5 years', salary: { min: 55000, max: 80000, currency: 'USD' }, location: 'Remote', skills: ['TESOL/CELTA', 'Online Teaching', 'Curriculum Design'], type: 'full-time' },
    { title: 'Education Data Analyst', category: 'education', company: 'Coursera', experience: '2-5 years', salary: { min: 80000, max: 115000, currency: 'USD' }, location: 'Remote', skills: ['Python', 'Learning Analytics', 'Tableau'], type: 'full-time' },
    { title: 'STEM Educator', category: 'education', company: 'Byju\'s', experience: '2-5 years', salary: { min: 650000, max: 1100000, currency: 'INR' }, location: 'Remote', skills: ['STEM Curriculum', 'Experiential Learning', 'Lab Skills'], type: 'full-time' },
    { title: 'Admissions Counselor', category: 'education', company: 'Coursera', experience: '2-4 years', salary: { min: 60000, max: 85000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['Admissions', 'Student Outreach', 'CRM'], type: 'full-time' },
    { title: 'EdTech Sales Manager', category: 'education', company: 'Byju\'s', experience: '4-8 years', salary: { min: 1000000, max: 1800000, currency: 'INR' }, location: 'Mumbai, India', skills: ['B2C Sales', 'Education Sales', 'Pipeline Management'], type: 'full-time' },
    { title: 'School Principal', category: 'education', company: 'Byju\'s', experience: '10-15 years', salary: { min: 2000000, max: 3500000, currency: 'INR' }, location: 'Delhi, India', skills: ['School Leadership', 'Curriculum Management', 'Faculty Development'], type: 'full-time' },
    { title: 'Content Writer – Education', category: 'education', company: 'Coursera', experience: '1-3 years', salary: { min: 55000, max: 80000, currency: 'USD' }, location: 'Remote', skills: ['Academic Writing', 'Research', 'SEO'], type: 'full-time' },
    { title: 'Tutoring Platform Engineer', category: 'education', company: 'Byju\'s', experience: '2-5 years', salary: { min: 1000000, max: 1800000, currency: 'INR' }, location: 'Bangalore, India', skills: ['React', 'Node.js', 'WebRTC'], type: 'full-time' },
    { title: 'Head of Academics', category: 'education', company: 'Byju\'s', experience: '12-18 years', salary: { min: 3500000, max: 6000000, currency: 'INR' }, location: 'Bangalore, India', skills: ['Academic Leadership', 'Policy Making', 'Faculty Management'], type: 'full-time' },
    { title: 'Instructional Coach', category: 'education', company: 'Coursera', experience: '4-7 years', salary: { min: 80000, max: 115000, currency: 'USD' }, location: 'Remote', skills: ['Coaching', 'Instructional Strategies', 'Professional Development'], type: 'full-time' },
    { title: 'Research Assistant – Education', category: 'education', company: 'Coursera', experience: '0-2 years', salary: { min: 45000, max: 65000, currency: 'USD' }, location: 'Remote', skills: ['Literature Review', 'Data Collection', 'Academic Writing'], type: 'part-time' },
    { title: 'Blended Learning Coordinator', category: 'education', company: 'Microsoft', experience: '3-6 years', salary: { min: 80000, max: 115000, currency: 'USD' }, location: 'Redmond, WA', skills: ['Blended Learning', 'Teams', 'Instructional Design'], type: 'full-time' },
    { title: 'Education Partnership Manager', category: 'education', company: 'Coursera', experience: '5-9 years', salary: { min: 110000, max: 160000, currency: 'USD' }, location: 'Remote', skills: ['University Partnerships', 'Contract Negotiation', 'B2B'], type: 'full-time' },

    // ─── SALES ────────────────────────────────────────────────────
    { title: 'Account Executive', category: 'sales', company: 'Salesforce', experience: '3-6 years', salary: { min: 120000, max: 200000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['CRM', 'B2B Sales', 'Pipeline Management'], type: 'full-time' },
    { title: 'Sales Development Representative', category: 'sales', company: 'HubSpot', experience: '0-2 years', salary: { min: 55000, max: 80000, currency: 'USD' }, location: 'Boston, MA', skills: ['Cold Calling', 'Email Outreach', 'HubSpot CRM'], type: 'full-time' },
    { title: 'Regional Sales Manager', category: 'sales', company: 'Microsoft', experience: '6-10 years', salary: { min: 150000, max: 220000, currency: 'USD' }, location: 'Chicago, IL', skills: ['Team Leadership', 'Revenue Growth', 'Territory Management'], type: 'full-time' },
    { title: 'Inside Sales Representative', category: 'sales', company: 'Infosys', experience: '1-3 years', salary: { min: 700000, max: 1200000, currency: 'INR' }, location: 'Bangalore, India', skills: ['Lead Generation', 'CRM', 'Product Demo'], type: 'full-time' },
    { title: 'Enterprise Sales Director', category: 'sales', company: 'Salesforce', experience: '10-15 years', salary: { min: 220000, max: 320000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Enterprise Deals', 'C-Level Relationships', 'Complex Selling'], type: 'full-time' },
    { title: 'Pre-Sales Consultant', category: 'sales', company: 'TCS', experience: '3-7 years', salary: { min: 1200000, max: 2200000, currency: 'INR' }, location: 'Mumbai, India', skills: ['Solution Design', 'RFP Response', 'Technical Demo'], type: 'full-time' },
    { title: 'Sales Operations Manager', category: 'sales', company: 'Salesforce', experience: '5-8 years', salary: { min: 120000, max: 170000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['SFDC Admin', 'Forecasting', 'Process Design'], type: 'full-time' },
    { title: 'Channel Partner Manager', category: 'sales', company: 'Microsoft', experience: '5-9 years', salary: { min: 130000, max: 185000, currency: 'USD' }, location: 'Redmond, WA', skills: ['Partner Enablement', 'Co-Selling', 'GTM Strategy'], type: 'full-time' },
    { title: 'Business Development Manager', category: 'sales', company: 'Uber', experience: '4-8 years', salary: { min: 120000, max: 175000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Deal Origination', 'Negotiation', 'Relationship Building'], type: 'full-time' },
    { title: 'Customer Success Manager', category: 'sales', company: 'HubSpot', experience: '3-6 years', salary: { min: 90000, max: 130000, currency: 'USD' }, location: 'Boston, MA', skills: ['Customer Retention', 'Upselling', 'Onboarding'], type: 'full-time' },
    { title: 'Retail Store Manager', category: 'sales', company: 'Apple', experience: '5-9 years', salary: { min: 85000, max: 120000, currency: 'USD' }, location: 'Cupertino, CA', skills: ['Retail Management', 'Team Leadership', 'Inventory'], type: 'full-time' },
    { title: 'Medical Sales Representative', category: 'sales', company: 'Medtronic', experience: '2-5 years', salary: { min: 90000, max: 140000, currency: 'USD' }, location: 'Remote', skills: ['Medical Devices', 'Hospital Sales', 'Anatomy Knowledge'], type: 'full-time' },
    { title: 'Sales Analyst', category: 'sales', company: 'Amazon', experience: '2-4 years', salary: { min: 80000, max: 115000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Excel', 'Tableau', 'Sales Reporting'], type: 'full-time' },
    { title: 'Key Account Manager', category: 'sales', company: 'Wipro', experience: '5-9 years', salary: { min: 1500000, max: 2600000, currency: 'INR' }, location: 'Pune, India', skills: ['Account Planning', 'Revenue Management', 'Stakeholder Engagement'], type: 'full-time' },
    { title: 'VP of Sales', category: 'sales', company: 'Salesforce', experience: '12-18 years', salary: { min: 280000, max: 400000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Sales Leadership', 'Revenue Strategy', 'Hiring'], type: 'full-time' },
    { title: 'Sales Trainer', category: 'sales', company: 'HubSpot', experience: '4-7 years', salary: { min: 85000, max: 120000, currency: 'USD' }, location: 'Boston, MA', skills: ['Sales Training', 'Coaching', 'LMS'], type: 'full-time' },
    { title: 'Outbound Sales Executive', category: 'sales', company: 'Infosys', experience: '1-4 years', salary: { min: 600000, max: 1100000, currency: 'INR' }, location: 'Chennai, India', skills: ['Cold Calling', 'Appointment Setting', 'B2B'], type: 'full-time' },
    { title: 'Strategic Account Director', category: 'sales', company: 'Microsoft', experience: '10-14 years', salary: { min: 200000, max: 290000, currency: 'USD' }, location: 'New York, NY', skills: ['Strategic Accounts', 'Executive Engagement', 'Value Selling'], type: 'full-time' },
    { title: 'Telesales Executive', category: 'sales', company: 'Byju\'s', experience: '0-2 years', salary: { min: 300000, max: 600000, currency: 'INR' }, location: 'Bangalore, India', skills: ['Telesales', 'Persuasion', 'Target Achievement'], type: 'full-time' },
    { title: 'Sales Engineer', category: 'sales', company: 'Salesforce', experience: '4-8 years', salary: { min: 140000, max: 200000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Technical Sales', 'APIs', 'Demos'], type: 'full-time' },
    { title: 'Digital Sales Specialist', category: 'sales', company: 'Google', experience: '2-5 years', salary: { min: 100000, max: 150000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['Google Ads', 'Digital Strategy', 'Client Consulting'], type: 'full-time' },
    { title: 'New Business Development Executive', category: 'sales', company: 'TCS', experience: '3-6 years', salary: { min: 1000000, max: 1800000, currency: 'INR' }, location: 'Delhi, India', skills: ['Lead Nurturing', 'Proposal Writing', 'IT Sales'], type: 'full-time' },
    { title: 'Field Sales Representative', category: 'sales', company: 'Amazon', experience: '2-4 years', salary: { min: 65000, max: 90000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Door-to-Door', 'Territory Planning', 'Field CRM'], type: 'full-time' },
    { title: 'Renewals Manager', category: 'sales', company: 'Salesforce', experience: '3-6 years', salary: { min: 100000, max: 145000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Renewals', 'Churn Prevention', 'Contract Negotiation'], type: 'full-time' },
    { title: 'Partner Sales Executive', category: 'sales', company: 'HubSpot', experience: '4-7 years', salary: { min: 100000, max: 150000, currency: 'USD' }, location: 'Remote', skills: ['Agency Partnerships', 'Revenue Sharing', 'Partner Training'], type: 'full-time' },

    // ─── ENGINEERING ──────────────────────────────────────────────
    { title: 'Mechanical Engineer', category: 'engineering', company: 'Siemens', experience: '2-5 years', salary: { min: 70000, max: 105000, currency: 'USD' }, location: 'Munich, Germany', skills: ['CAD/CAM', 'SolidWorks', 'FEA'], type: 'full-time' },
    { title: 'Electrical Engineer', category: 'engineering', company: 'Bosch', experience: '3-6 years', salary: { min: 75000, max: 115000, currency: 'USD' }, location: 'Stuttgart, Germany', skills: ['Circuit Design', 'PCB Layout', 'Embedded Systems'], type: 'full-time' },
    { title: 'Civil Engineer', category: 'engineering', company: 'L&T', experience: '2-5 years', salary: { min: 700000, max: 1400000, currency: 'INR' }, location: 'Mumbai, India', skills: ['AutoCAD', 'Structural Analysis', 'Project Management'], type: 'full-time' },
    { title: 'Controls Engineer', category: 'engineering', company: 'Siemens', experience: '4-8 years', salary: { min: 90000, max: 135000, currency: 'USD' }, location: 'Munich, Germany', skills: ['PLC Programming', 'SCADA', 'HMI'], type: 'full-time' },
    { title: 'Manufacturing Engineer', category: 'engineering', company: 'Bosch', experience: '3-7 years', salary: { min: 80000, max: 120000, currency: 'USD' }, location: 'Stuttgart, Germany', skills: ['Lean Manufacturing', 'Six Sigma', 'Process Optimization'], type: 'full-time' },
    { title: 'Chemical Engineer', category: 'engineering', company: 'L&T', experience: '3-6 years', salary: { min: 800000, max: 1600000, currency: 'INR' }, location: 'Pune, India', skills: ['Process Engineering', 'HAZOP', 'Aspen Plus'], type: 'full-time' },
    { title: 'Structural Engineer', category: 'engineering', company: 'L&T', experience: '4-8 years', salary: { min: 1000000, max: 2000000, currency: 'INR' }, location: 'Mumbai, India', skills: ['STAAD.Pro', 'Foundation Design', 'Seismic Analysis'], type: 'full-time' },
    { title: 'Aerospace Engineer', category: 'engineering', company: 'Siemens', experience: '5-9 years', salary: { min: 110000, max: 165000, currency: 'USD' }, location: 'Munich, Germany', skills: ['CFD', 'CATIA', 'Structural Mechanics'], type: 'full-time' },
    { title: 'Automation Engineer', category: 'engineering', company: 'Bosch', experience: '3-7 years', salary: { min: 85000, max: 125000, currency: 'USD' }, location: 'Stuttgart, Germany', skills: ['Robotic Automation', 'Python', 'PLC'], type: 'full-time' },
    { title: 'Environmental Engineer', category: 'engineering', company: 'L&T', experience: '4-7 years', salary: { min: 900000, max: 1700000, currency: 'INR' }, location: 'Chennai, India', skills: ['EIA', 'Waste Management', 'ISO 14001'], type: 'full-time' },
    { title: 'Quality Engineer', category: 'engineering', company: 'Bosch', experience: '3-6 years', salary: { min: 75000, max: 110000, currency: 'USD' }, location: 'Stuttgart, Germany', skills: ['PPAP', 'FMEA', 'Statistical Process Control'], type: 'full-time' },
    { title: 'Robotics Engineer', category: 'engineering', company: 'Siemens', experience: '4-8 years', salary: { min: 100000, max: 150000, currency: 'USD' }, location: 'Munich, Germany', skills: ['ROS', 'Computer Vision', 'C++'], type: 'full-time' },
    { title: 'Project Engineer', category: 'engineering', company: 'L&T', experience: '3-7 years', salary: { min: 900000, max: 1800000, currency: 'INR' }, location: 'Delhi, India', skills: ['Project Scheduling', 'MS Project', 'Budgeting'], type: 'full-time' },
    { title: 'Network Engineer', category: 'engineering', company: 'Siemens', experience: '3-6 years', salary: { min: 85000, max: 125000, currency: 'USD' }, location: 'Munich, Germany', skills: ['Cisco', 'Routing & Switching', 'Network Security'], type: 'full-time' },
    { title: 'Firmware Engineer', category: 'engineering', company: 'Bosch', experience: '3-7 years', salary: { min: 90000, max: 135000, currency: 'USD' }, location: 'Stuttgart, Germany', skills: ['C/C++', 'RTOS', 'Microcontrollers'], type: 'full-time' },
    { title: 'Systems Engineer', category: 'engineering', company: 'Siemens', experience: '5-9 years', salary: { min: 100000, max: 150000, currency: 'USD' }, location: 'Munich, Germany', skills: ['System Architecture', 'MBSE', 'Requirements Engineering'], type: 'full-time' },
    { title: 'Oil & Gas Engineer', category: 'engineering', company: 'L&T', experience: '5-10 years', salary: { min: 1400000, max: 2800000, currency: 'INR' }, location: 'Mumbai, India', skills: ['Pipeline Design', 'P&ID', 'Safety Engineering'], type: 'full-time' },
    { title: 'Test Engineer', category: 'engineering', company: 'Bosch', experience: '2-5 years', salary: { min: 70000, max: 100000, currency: 'USD' }, location: 'Stuttgart, Germany', skills: ['Test Planning', 'Hardware Testing', 'Bug Tracking'], type: 'full-time' },
    { title: 'R&D Engineer', category: 'engineering', company: 'Siemens', experience: '4-8 years', salary: { min: 95000, max: 140000, currency: 'USD' }, location: 'Munich, Germany', skills: ['Innovation', 'Prototyping', 'Patent Writing'], type: 'full-time' },
    { title: 'Energy Engineer', category: 'engineering', company: 'Siemens', experience: '4-8 years', salary: { min: 90000, max: 135000, currency: 'USD' }, location: 'Munich, Germany', skills: ['Renewable Energy', 'Grid Analysis', 'ETAP'], type: 'full-time' },
    { title: 'Welding Engineer', category: 'engineering', company: 'L&T', experience: '3-6 years', salary: { min: 700000, max: 1300000, currency: 'INR' }, location: 'Chennai, India', skills: ['AWS Certified', 'Non-Destructive Testing', 'Welding Standards'], type: 'full-time' },
    { title: 'Site Engineer', category: 'engineering', company: 'L&T', experience: '2-5 years', salary: { min: 600000, max: 1100000, currency: 'INR' }, location: 'Hyderabad, India', skills: ['Site Supervision', 'Safety Management', 'Construction Methods'], type: 'full-time' },
    { title: 'Hardware Engineer', category: 'engineering', company: 'Bosch', experience: '3-6 years', salary: { min: 85000, max: 125000, currency: 'USD' }, location: 'Stuttgart, Germany', skills: ['Schematic Design', 'FPGA', 'Signal Integrity'], type: 'full-time' },
    { title: 'Validation Engineer', category: 'engineering', company: 'Siemens', experience: '3-7 years', salary: { min: 85000, max: 125000, currency: 'USD' }, location: 'Munich, Germany', skills: ['V&V', 'IEC 61511', 'Safety Cases'], type: 'full-time' },
    { title: 'Graduate Engineer Trainee', category: 'engineering', company: 'L&T', experience: '0-1 years', salary: { min: 400000, max: 650000, currency: 'INR' }, location: 'Mumbai, India', skills: ['Engineering Fundamentals', 'AutoCAD', 'Teamwork'], type: 'full-time' },

    // ─── HUMAN RESOURCES ──────────────────────────────────────────
    { title: 'HR Business Partner', category: 'hr', company: 'Google', experience: '6-10 years', salary: { min: 140000, max: 210000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['Strategic HR', 'Talent Management', 'Legal Compliance'], type: 'full-time' },
    { title: 'Talent Acquisition Specialist', category: 'hr', company: 'Microsoft', experience: '3-6 years', salary: { min: 90000, max: 135000, currency: 'USD' }, location: 'Redmond, WA', skills: ['Full-Cycle Recruiting', 'LinkedIn Sourcing', 'ATS'], type: 'full-time' },
    { title: 'HR Manager', category: 'hr', company: 'TCS', experience: '5-8 years', salary: { min: 1200000, max: 2200000, currency: 'INR' }, location: 'Chennai, India', skills: ['Recruitment', 'Employee Relations', 'HRIS'], type: 'full-time' },
    { title: 'Compensation & Benefits Analyst', category: 'hr', company: 'Amazon', experience: '3-6 years', salary: { min: 100000, max: 145000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Pay Benchmarking', 'Benefits Administration', 'Radford'], type: 'full-time' },
    { title: 'Learning & Development Manager', category: 'hr', company: 'Deloitte', experience: '5-9 years', salary: { min: 110000, max: 160000, currency: 'USD' }, location: 'Chicago, IL', skills: ['Training Programs', 'LMS', 'Leadership Development'], type: 'full-time' },
    { title: 'HR Generalist', category: 'hr', company: 'Wipro', experience: '2-5 years', salary: { min: 700000, max: 1300000, currency: 'INR' }, location: 'Pune, India', skills: ['Onboarding', 'Payroll', 'Policy Implementation'], type: 'full-time' },
    { title: 'Diversity, Equity & Inclusion Lead', category: 'hr', company: 'Meta', experience: '6-10 years', salary: { min: 140000, max: 200000, currency: 'USD' }, location: 'Menlo Park, CA', skills: ['DEI Strategy', 'Culture Change', 'Inclusive Hiring'], type: 'full-time' },
    { title: 'Recruiter', category: 'hr', company: 'Infosys', experience: '1-3 years', salary: { min: 500000, max: 900000, currency: 'INR' }, location: 'Bangalore, India', skills: ['Sourcing', 'Interview Coordination', 'Job Portals'], type: 'full-time' },
    { title: 'Employee Engagement Specialist', category: 'hr', company: 'Netflix', experience: '3-6 years', salary: { min: 90000, max: 130000, currency: 'USD' }, location: 'Los Gatos, CA', skills: ['Culture Programs', 'Pulse Surveys', 'Event Management'], type: 'full-time' },
    { title: 'HRIS Administrator', category: 'hr', company: 'Amazon', experience: '2-5 years', salary: { min: 80000, max: 115000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Workday', 'SAP SuccessFactors', 'HR Data Analytics'], type: 'full-time' },
    { title: 'People Analytics Manager', category: 'hr', company: 'Google', experience: '5-9 years', salary: { min: 140000, max: 200000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['People Analytics', 'Python', 'Tableau'], type: 'full-time' },
    { title: 'Labor Relations Specialist', category: 'hr', company: 'L&T', experience: '5-9 years', salary: { min: 1200000, max: 2000000, currency: 'INR' }, location: 'Mumbai, India', skills: ['Union Negotiations', 'Labour Law', 'Grievance Handling'], type: 'full-time' },
    { title: 'Chief People Officer', category: 'hr', company: 'Airbnb', experience: '15+ years', salary: { min: 350000, max: 500000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Executive HR Leadership', 'Culture Design', 'Org Strategy'], type: 'full-time' },
    { title: 'HR Operations Coordinator', category: 'hr', company: 'TCS', experience: '1-3 years', salary: { min: 400000, max: 700000, currency: 'INR' }, location: 'Hyderabad, India', skills: ['HR Operations', 'Compliance', 'Document Management'], type: 'full-time' },
    { title: 'Organizational Development Consultant', category: 'hr', company: 'Deloitte', experience: '7-12 years', salary: { min: 140000, max: 200000, currency: 'USD' }, location: 'Chicago, IL', skills: ['OD Interventions', 'Change Management', 'Coaching'], type: 'full-time' },
    { title: 'HR Technology Lead', category: 'hr', company: 'Microsoft', experience: '6-10 years', salary: { min: 140000, max: 200000, currency: 'USD' }, location: 'Redmond, WA', skills: ['HR Tech Implementation', 'Vendor Management', 'Process Automation'], type: 'full-time' },
    { title: 'Workforce Planning Analyst', category: 'hr', company: 'Amazon', experience: '3-6 years', salary: { min: 95000, max: 135000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Headcount Planning', 'Forecasting', 'Workday'], type: 'full-time' },
    { title: 'HR Intern', category: 'hr', company: 'Wipro', experience: '0-1 years', salary: { min: 200000, max: 350000, currency: 'INR' }, location: 'Bangalore, India', skills: ['MS Office', 'Communication', 'HR Basics'], type: 'internship' },
    { title: 'Benefits Manager', category: 'hr', company: 'Google', experience: '6-10 years', salary: { min: 130000, max: 185000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['Health Benefits', 'Retirement Plans', 'Benefits Benchmarking'], type: 'full-time' },
    { title: 'Talent Development Lead', category: 'hr', company: 'Meta', experience: '6-10 years', salary: { min: 140000, max: 200000, currency: 'USD' }, location: 'Menlo Park, CA', skills: ['Career Frameworks', 'Succession Planning', 'Coaching'], type: 'full-time' },
    { title: 'HR Compliance Manager', category: 'hr', company: 'JPMorgan', experience: '6-10 years', salary: { min: 130000, max: 185000, currency: 'USD' }, location: 'New York, NY', skills: ['Employment Law', 'Audits', 'Policy Writing'], type: 'full-time' },
    { title: 'Sourcing Specialist', category: 'hr', company: 'Infosys', experience: '2-4 years', salary: { min: 600000, max: 1100000, currency: 'INR' }, location: 'Bangalore, India', skills: ['LinkedIn Recruiter', 'Boolean Search', 'Naukri.com'], type: 'full-time' },
    { title: 'Onboarding Specialist', category: 'hr', company: 'Netflix', experience: '2-4 years', salary: { min: 70000, max: 100000, currency: 'USD' }, location: 'Los Gatos, CA', skills: ['New Hire Orientation', 'Culture Assimilation', 'Process Design'], type: 'full-time' },
    { title: 'HR Director', category: 'hr', company: 'Amazon', experience: '12-18 years', salary: { min: 220000, max: 320000, currency: 'USD' }, location: 'Seattle, WA', skills: ['HR Strategy', 'Talent Planning', 'Executive Coaching'], type: 'full-time' },
    { title: 'Performance Management Specialist', category: 'hr', company: 'TCS', experience: '4-8 years', salary: { min: 1000000, max: 1800000, currency: 'INR' }, location: 'Mumbai, India', skills: ['KPI Setting', 'Review Systems', 'Calibration'], type: 'full-time' },

    // ─── LEGAL ────────────────────────────────────────────────────
    { title: 'Corporate Lawyer', category: 'legal', company: 'Goldman Sachs', experience: '5-9 years', salary: { min: 180000, max: 260000, currency: 'USD' }, location: 'New York, NY', skills: ['M&A Law', 'Contract Drafting', 'Securities'], type: 'full-time' },
    { title: 'Legal Counsel', category: 'legal', company: 'Microsoft', experience: '7-12 years', salary: { min: 190000, max: 280000, currency: 'USD' }, location: 'Redmond, WA', skills: ['Technology Law', 'IP', 'Privacy'], type: 'full-time' },
    { title: 'Compliance Analyst', category: 'legal', company: 'JPMorgan', experience: '3-6 years', salary: { min: 100000, max: 150000, currency: 'USD' }, location: 'New York, NY', skills: ['Regulatory Compliance', 'AML', 'Risk Controls'], type: 'full-time' },
    { title: 'IP Attorney', category: 'legal', company: 'Apple', experience: '6-10 years', salary: { min: 200000, max: 290000, currency: 'USD' }, location: 'Cupertino, CA', skills: ['Patent Prosecution', 'Trademark', 'Licensing'], type: 'full-time' },
    { title: 'Contract Manager', category: 'legal', company: 'Amazon', experience: '4-8 years', salary: { min: 110000, max: 160000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Contract Lifecycle', 'CLM Tools', 'Negotiation'], type: 'full-time' },
    { title: 'Privacy Counsel', category: 'legal', company: 'Google', experience: '6-10 years', salary: { min: 200000, max: 290000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['GDPR', 'CCPA', 'Privacy by Design'], type: 'full-time' },
    { title: 'Legal Operations Manager', category: 'legal', company: 'Salesforce', experience: '5-9 years', salary: { min: 140000, max: 200000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Legal Tech', 'Process Improvement', 'e-Billing'], type: 'full-time' },
    { title: 'Employment Lawyer', category: 'legal', company: 'Deloitte', experience: '5-10 years', salary: { min: 160000, max: 230000, currency: 'USD' }, location: 'Chicago, IL', skills: ['Employment Law', 'Litigation', 'EEOC'], type: 'full-time' },
    { title: 'Legal Analyst', category: 'legal', company: 'Wipro', experience: '2-5 years', salary: { min: 800000, max: 1500000, currency: 'INR' }, location: 'Bangalore, India', skills: ['Contract Review', 'Legal Research', 'Due Diligence'], type: 'full-time' },
    { title: 'Paralegal', category: 'legal', company: 'JPMorgan', experience: '1-3 years', salary: { min: 65000, max: 90000, currency: 'USD' }, location: 'New York, NY', skills: ['Legal Documentation', 'Court Filings', 'Research'], type: 'full-time' },
    { title: 'Regulatory Lawyer', category: 'legal', company: 'Medtronic', experience: '6-10 years', salary: { min: 190000, max: 270000, currency: 'USD' }, location: 'Dublin, Ireland', skills: ['FDA Law', 'MDR', 'Regulatory Strategy'], type: 'full-time' },
    { title: 'General Counsel', category: 'legal', company: 'Netflix', experience: '15+ years', salary: { min: 400000, max: 600000, currency: 'USD' }, location: 'Los Gatos, CA', skills: ['Corporate Governance', 'Board Advisory', 'M&A'], type: 'full-time' },
    { title: 'Anti-Bribery & Corruption Specialist', category: 'legal', company: 'Goldman Sachs', experience: '5-9 years', salary: { min: 130000, max: 190000, currency: 'USD' }, location: 'New York, NY', skills: ['ABC Compliance', 'Investigations', 'FCPA'], type: 'full-time' },
    { title: 'Environmental Compliance Officer', category: 'legal', company: 'Siemens', experience: '5-9 years', salary: { min: 100000, max: 145000, currency: 'USD' }, location: 'Munich, Germany', skills: ['Environmental Law', 'ISO 14001', 'REACH'], type: 'full-time' },
    { title: 'Technology Transactions Lawyer', category: 'legal', company: 'Microsoft', experience: '6-10 years', salary: { min: 200000, max: 285000, currency: 'USD' }, location: 'Redmond, WA', skills: ['SaaS Agreements', 'Open Source', 'Cloud Contracts'], type: 'full-time' },
    { title: 'Trade Compliance Manager', category: 'legal', company: 'Amazon', experience: '6-10 years', salary: { min: 130000, max: 185000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Export Controls', 'ITAR', 'Customs Law'], type: 'full-time' },
    { title: 'Legal Secretary', category: 'legal', company: 'Deloitte', experience: '1-3 years', salary: { min: 50000, max: 70000, currency: 'USD' }, location: 'Chicago, IL', skills: ['Legal Admin', 'Document Management', 'Scheduling'], type: 'full-time' },
    { title: 'Litigation Support Analyst', category: 'legal', company: 'JPMorgan', experience: '2-5 years', salary: { min: 80000, max: 115000, currency: 'USD' }, location: 'New York, NY', skills: ['eDiscovery', 'Relativity', 'Document Review'], type: 'full-time' },
    { title: 'Corporate Secretary', category: 'legal', company: 'Wipro', experience: '5-9 years', salary: { min: 1500000, max: 2500000, currency: 'INR' }, location: 'Pune, India', skills: ['Company Secretarial', 'Board Management', 'SEBI Compliance'], type: 'full-time' },
    { title: 'Data Privacy Officer', category: 'legal', company: 'Meta', experience: '8-12 years', salary: { min: 210000, max: 300000, currency: 'USD' }, location: 'Menlo Park, CA', skills: ['DPO', 'GDPR', 'Privacy Framework'], type: 'full-time' },
    { title: 'Insurance Lawyer', category: 'legal', company: 'JPMorgan', experience: '5-9 years', salary: { min: 160000, max: 230000, currency: 'USD' }, location: 'New York, NY', skills: ['Insurance Law', 'Coverage Disputes', 'Claims Management'], type: 'full-time' },
    { title: 'Legal Risk Manager', category: 'legal', company: 'Goldman Sachs', experience: '8-12 years', salary: { min: 190000, max: 270000, currency: 'USD' }, location: 'New York, NY', skills: ['Legal Risk', 'Governance', 'Enterprise Risk'], type: 'full-time' },
    { title: 'Mergers & Acquisitions Counsel', category: 'legal', company: 'Goldman Sachs', experience: '6-10 years', salary: { min: 220000, max: 310000, currency: 'USD' }, location: 'New York, NY', skills: ['M&A', 'Due Diligence', 'Share Purchase Agreements'], type: 'full-time' },
    { title: 'Cybersecurity Legal Advisor', category: 'legal', company: 'Microsoft', experience: '6-10 years', salary: { min: 200000, max: 285000, currency: 'USD' }, location: 'Redmond, WA', skills: ['Cyber Law', 'Incident Response Law', 'NIST Framework'], type: 'full-time' },
    { title: 'Legal Intern', category: 'legal', company: 'Deloitte', experience: '0-1 years', salary: { min: 45000, max: 65000, currency: 'USD' }, location: 'Chicago, IL', skills: ['Legal Research', 'Memo Writing', 'MS Word'], type: 'internship' },

    // ─── OPERATIONS ───────────────────────────────────────────────
    { title: 'Operations Manager', category: 'operations', company: 'Amazon', experience: '5-9 years', salary: { min: 110000, max: 175000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Process Improvement', 'Team Leadership', 'Risk Management'], type: 'full-time' },
    { title: 'Supply Chain Manager', category: 'operations', company: 'Apple', experience: '6-10 years', salary: { min: 140000, max: 200000, currency: 'USD' }, location: 'Cupertino, CA', skills: ['Supply Chain', 'ERP', 'Vendor Management'], type: 'full-time' },
    { title: 'Logistics Coordinator', category: 'operations', company: 'Amazon', experience: '2-4 years', salary: { min: 70000, max: 100000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Freight Management', 'SAP TM', 'Route Planning'], type: 'full-time' },
    { title: 'Business Operations Analyst', category: 'operations', company: 'Google', experience: '2-5 years', salary: { min: 100000, max: 145000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['Process Analysis', 'SQL', 'Dashboard Reporting'], type: 'full-time' },
    { title: 'Procurement Manager', category: 'operations', company: 'Siemens', experience: '5-9 years', salary: { min: 95000, max: 140000, currency: 'USD' }, location: 'Munich, Germany', skills: ['Strategic Sourcing', 'Supplier Negotiation', 'SAP MM'], type: 'full-time' },
    { title: 'Warehouse Manager', category: 'operations', company: 'Amazon', experience: '5-9 years', salary: { min: 80000, max: 115000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Warehouse Management', 'LEAN', 'Safety Compliance'], type: 'full-time' },
    { title: 'Director of Operations', category: 'operations', company: 'Airbnb', experience: '10-15 years', salary: { min: 200000, max: 290000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Operational Strategy', 'P&L', 'Cross-Functional Leadership'], type: 'full-time' },
    { title: 'IT Operations Engineer', category: 'operations', company: 'Microsoft', experience: '3-6 years', salary: { min: 100000, max: 145000, currency: 'USD' }, location: 'Redmond, WA', skills: ['ITIL', 'Incident Management', 'Azure Operations'], type: 'full-time' },
    { title: 'Facilities Manager', category: 'operations', company: 'TCS', experience: '5-9 years', salary: { min: 1200000, max: 2200000, currency: 'INR' }, location: 'Mumbai, India', skills: ['Facilities Management', 'Vendor Coordination', 'Safety'], type: 'full-time' },
    { title: 'Customer Operations Specialist', category: 'operations', company: 'Uber', experience: '2-4 years', salary: { min: 70000, max: 100000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['CRM', 'Escalation Management', 'Process Documentation'], type: 'full-time' },
    { title: 'Quality Operations Manager', category: 'operations', company: 'Bosch', experience: '6-10 years', salary: { min: 100000, max: 150000, currency: 'USD' }, location: 'Stuttgart, Germany', skills: ['Quality Systems', 'ISO 9001', 'Continuous Improvement'], type: 'full-time' },
    { title: 'ERP Implementation Consultant', category: 'operations', company: 'Deloitte', experience: '4-8 years', salary: { min: 110000, max: 160000, currency: 'USD' }, location: 'Chicago, IL', skills: ['SAP ERP', 'Business Process Mapping', 'Change Management'], type: 'full-time' },
    { title: 'Fleet Operations Manager', category: 'operations', company: 'Uber', experience: '4-8 years', salary: { min: 90000, max: 130000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Fleet Management', 'GPS Systems', 'Cost Optimization'], type: 'full-time' },
    { title: 'Strategic Planning Manager', category: 'operations', company: 'Microsoft', experience: '7-12 years', salary: { min: 160000, max: 230000, currency: 'USD' }, location: 'Redmond, WA', skills: ['Strategic Planning', 'OKRs', 'Business Intelligence'], type: 'full-time' },
    { title: 'Process Excellence Lead', category: 'operations', company: 'TCS', experience: '6-10 years', salary: { min: 1800000, max: 3000000, currency: 'INR' }, location: 'Bangalore, India', skills: ['Six Sigma Black Belt', 'LEAN', 'Process Mapping'], type: 'full-time' },
    { title: 'Vendor Relations Manager', category: 'operations', company: 'Amazon', experience: '4-8 years', salary: { min: 100000, max: 145000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Vendor Management', 'Contract Management', 'SLA Monitoring'], type: 'full-time' },
    { title: 'Office Manager', category: 'operations', company: 'Airbnb', experience: '3-5 years', salary: { min: 75000, max: 105000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Office Administration', 'Event Planning', 'Budget Management'], type: 'full-time' },
    { title: 'Operations Analyst', category: 'operations', company: 'Google', experience: '2-4 years', salary: { min: 90000, max: 130000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['Data Analysis', 'Reporting', 'Process Optimization'], type: 'full-time' },
    { title: 'Program Operations Manager', category: 'operations', company: 'Meta', experience: '5-9 years', salary: { min: 130000, max: 190000, currency: 'USD' }, location: 'Menlo Park, CA', skills: ['Program Management', 'Cross-Functional Coordination', 'Agile'], type: 'full-time' },
    { title: 'Customer Support Lead', category: 'operations', company: 'Salesforce', experience: '3-6 years', salary: { min: 85000, max: 120000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Support Operations', 'Team Management', 'CSAT'], type: 'full-time' },
    { title: 'Inventory Manager', category: 'operations', company: 'Apple', experience: '4-8 years', salary: { min: 100000, max: 145000, currency: 'USD' }, location: 'Cupertino, CA', skills: ['Inventory Management', 'ERP', 'Demand Planning'], type: 'full-time' },
    { title: 'BPO Operations Manager', category: 'operations', company: 'Wipro', experience: '5-9 years', salary: { min: 1400000, max: 2400000, currency: 'INR' }, location: 'Hyderabad, India', skills: ['BPO Management', 'KPI Monitoring', 'Workforce Management'], type: 'full-time' },
    { title: 'Field Operations Coordinator', category: 'operations', company: 'Uber', experience: '2-4 years', salary: { min: 65000, max: 90000, currency: 'USD' }, location: 'Remote', skills: ['Field Coordination', 'Reporting', 'Issue Resolution'], type: 'full-time' },
    { title: 'COO', category: 'operations', company: 'Airbnb', experience: '15+ years', salary: { min: 450000, max: 650000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Executive Operations', 'Scale-Up Experience', 'Metrics-Driven'], type: 'full-time' },
    { title: 'Operations Intern', category: 'operations', company: 'Amazon', experience: '0-1 years', salary: { min: 50000, max: 70000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Excel', 'Process Documentation', 'Data Entry'], type: 'internship' },

    // ─── DATA SCIENCE ─────────────────────────────────────────────
    { title: 'Data Scientist', category: 'data-science', company: 'Google', experience: '3-6 years', salary: { min: 150000, max: 220000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['Python', 'Machine Learning', 'BigQuery'], type: 'full-time' },
    { title: 'Machine Learning Researcher', category: 'data-science', company: 'Meta', experience: '4-8 years', salary: { min: 180000, max: 270000, currency: 'USD' }, location: 'Menlo Park, CA', skills: ['Deep Learning', 'PyTorch', 'NLP'], type: 'full-time' },
    { title: 'Data Analyst', category: 'data-science', company: 'Amazon', experience: '2-4 years', salary: { min: 100000, max: 145000, currency: 'USD' }, location: 'Seattle, WA', skills: ['SQL', 'Python', 'Tableau'], type: 'full-time' },
    { title: 'AI Research Scientist', category: 'data-science', company: 'Google', experience: '5-10 years', salary: { min: 200000, max: 300000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['Deep Learning', 'Transformers', 'Research Publication'], type: 'full-time' },
    { title: 'NLP Engineer', category: 'data-science', company: 'Amazon', experience: '3-6 years', salary: { min: 160000, max: 230000, currency: 'USD' }, location: 'Seattle, WA', skills: ['NLP', 'Transformers', 'BERT'], type: 'full-time' },
    { title: 'Data Science Lead', category: 'data-science', company: 'Netflix', experience: '7-12 years', salary: { min: 200000, max: 290000, currency: 'USD' }, location: 'Los Gatos, CA', skills: ['Team Leadership', 'ML Strategy', 'Python'], type: 'full-time' },
    { title: 'Computer Vision Engineer', category: 'data-science', company: 'Meta', experience: '3-7 years', salary: { min: 170000, max: 250000, currency: 'USD' }, location: 'Menlo Park, CA', skills: ['OpenCV', 'CNNs', 'PyTorch'], type: 'full-time' },
    { title: 'Business Intelligence Developer', category: 'data-science', company: 'Microsoft', experience: '3-6 years', salary: { min: 115000, max: 165000, currency: 'USD' }, location: 'Redmond, WA', skills: ['Power BI', 'DAX', 'SQL'], type: 'full-time' },
    { title: 'Data Science Consultant', category: 'data-science', company: 'Deloitte', experience: '4-8 years', salary: { min: 130000, max: 190000, currency: 'USD' }, location: 'Chicago, IL', skills: ['Statistical Modeling', 'Python', 'Client Consulting'], type: 'full-time' },
    { title: 'MLOps Engineer', category: 'data-science', company: 'Uber', experience: '3-7 years', salary: { min: 150000, max: 220000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['MLflow', 'Kubernetes', 'Feature Stores'], type: 'full-time' },
    { title: 'Quantitative Researcher', category: 'data-science', company: 'Goldman Sachs', experience: '3-7 years', salary: { min: 170000, max: 250000, currency: 'USD' }, location: 'New York, NY', skills: ['Statistics', 'Python', 'Financial Modeling'], type: 'full-time' },
    { title: 'Data Engineering Manager', category: 'data-science', company: 'Google', experience: '7-12 years', salary: { min: 200000, max: 280000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['Data Pipelines', 'BigQuery', 'Team Management'], type: 'full-time' },
    { title: 'DataOps Engineer', category: 'data-science', company: 'Amazon', experience: '3-6 years', salary: { min: 130000, max: 190000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Airflow', 'dbt', 'Spark'], type: 'full-time' },
    { title: 'Analytics Engineer', category: 'data-science', company: 'Airbnb', experience: '3-6 years', salary: { min: 140000, max: 200000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['dbt', 'SQL', 'Looker'], type: 'full-time' },
    { title: 'Data Privacy Analyst', category: 'data-science', company: 'Microsoft', experience: '2-5 years', salary: { min: 100000, max: 145000, currency: 'USD' }, location: 'Redmond, WA', skills: ['Privacy Engineering', 'Data Classification', 'GDPR'], type: 'full-time' },
    { title: 'Research Scientist – Recommendation Systems', category: 'data-science', company: 'Netflix', experience: '4-8 years', salary: { min: 190000, max: 270000, currency: 'USD' }, location: 'Los Gatos, CA', skills: ['Collaborative Filtering', 'Personalization', 'TensorFlow'], type: 'full-time' },
    { title: 'Data Science Product Manager', category: 'data-science', company: 'Google', experience: '6-10 years', salary: { min: 180000, max: 260000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['AI Product Strategy', 'Roadmapping', 'Data Fluency'], type: 'full-time' },
    { title: 'Data Governance Analyst', category: 'data-science', company: 'JPMorgan', experience: '3-6 years', salary: { min: 110000, max: 155000, currency: 'USD' }, location: 'New York, NY', skills: ['Data Catalog', 'Metadata Management', 'Data Quality'], type: 'full-time' },
    { title: 'Time Series Analyst', category: 'data-science', company: 'Infosys', experience: '2-5 years', salary: { min: 1000000, max: 1800000, currency: 'INR' }, location: 'Bangalore, India', skills: ['ARIMA', 'Prophet', 'Demand Forecasting'], type: 'full-time' },
    { title: 'Geospatial Data Scientist', category: 'data-science', company: 'Uber', experience: '3-6 years', salary: { min: 140000, max: 200000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['GIS', 'PostGIS', 'Spatial Analytics'], type: 'full-time' },
    { title: 'Data Science Intern', category: 'data-science', company: 'Google', experience: '0-1 years', salary: { min: 90000, max: 120000, currency: 'USD' }, location: 'Mountain View, CA', skills: ['Python', 'Statistics', 'SQL'], type: 'internship' },
    { title: 'Clinical Data Scientist', category: 'data-science', company: 'Medtronic', experience: '4-8 years', salary: { min: 120000, max: 175000, currency: 'USD' }, location: 'Dublin, Ireland', skills: ['Biostatistics', 'R', 'Clinical Trials'], type: 'full-time' },
    { title: 'Text Analytics Engineer', category: 'data-science', company: 'Meta', experience: '3-6 years', salary: { min: 155000, max: 225000, currency: 'USD' }, location: 'Menlo Park, CA', skills: ['Text Mining', 'spaCy', 'Named Entity Recognition'], type: 'full-time' },
    { title: 'Data Quality Engineer', category: 'data-science', company: 'Salesforce', experience: '2-5 years', salary: { min: 110000, max: 155000, currency: 'USD' }, location: 'San Francisco, CA', skills: ['Great Expectations', 'Data Validation', 'Python'], type: 'full-time' },
    { title: 'Principal Data Scientist', category: 'data-science', company: 'Amazon', experience: '10-15 years', salary: { min: 260000, max: 380000, currency: 'USD' }, location: 'Seattle, WA', skills: ['Research Leadership', 'ML Architecture', 'Publications'], type: 'full-time' },
];

const seed = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('✅ Connected to MongoDB');

        const admin = await User.findOne({ role: 'admin' });
        if (!admin) {
            console.log('❌ No admin user found. Run seeder.js first.');
            process.exit(1);
        }

        // Ensure all companies exist
        const companyMap = {};
        for (const c of COMPANIES) {
            let comp = await Company.findOne({ name: c.name });
            if (!comp) {
                const slug = slugify(c.name + '-' + Date.now(), { lower: true });
                comp = await Company.create({
                    name: c.name, slug, industry: c.industry,
                    location: c.location, owner: admin._id, logo: c.logo,
                    description: `${c.name} — a global leader in ${c.industry}. Join us to build the future.`,
                    isActive: true, isVerified: true
                });
                console.log(`🏢 Created company: ${c.name}`);
            }
            companyMap[c.name] = comp._id;
        }

        let added = 0, skipped = 0;
        for (const job of JOBS) {
            const compId = companyMap[job.company];
            if (!compId) { console.log(`⚠️  Company not found: ${job.company}`); continue; }
            const exists = await Job.findOne({ title: job.title, company: compId });
            if (exists) { skipped++; continue; }
            const slug = slugify(`${job.title}-${job.company}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`, { lower: true });
            await Job.create({
                title: job.title, slug, category: job.category,
                company: compId, postedBy: admin._id,
                experience: job.experience, salary: job.salary,
                location: job.location, skills: job.skills,
                type: job.type || 'full-time',
                description: `We are looking for a talented ${job.title} at ${job.company}. This role requires ${job.experience} of experience. Key skills: ${job.skills.join(', ')}.`,
                requirements: [`${job.experience} of relevant experience`, ...job.skills.map(s => `Proficiency in ${s}`)],
                status: 'active'
            });
            added++;
        }

        console.log(`\n✅ Done! Added: ${added} jobs, Skipped (already exist): ${skipped}`);
        console.log('📊 Category breakdown:');
        const cats = ['technology','design','marketing','finance','healthcare','education','sales','engineering','hr','legal','operations','data-science'];
        for (const cat of cats) {
            const count = await Job.countDocuments({ category: cat, status: 'active' });
            console.log(`   ${cat.padEnd(14)} → ${count} jobs`);
        }
        process.exit(0);
    } catch (err) {
        console.error('❌ Error:', err.message);
        process.exit(1);
    }
};

seed();
